/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SidebarSection } from "./components/sidebar/sidebar";
import { default as SlButton } from "@shoelace-style/shoelace";
export { SidebarSection } from "./components/sidebar/sidebar";
export { default as SlButton } from "@shoelace-style/shoelace";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SharedSidebar {
        /**
          * @default false
         */
        "collapsed": boolean;
        /**
          * @default []
         */
        "sections": SidebarSection[];
    }
    interface UiButton {
        /**
          * Whether the button should have a caret
          * @default false
         */
        "caret": boolean;
        /**
          * Whether the button should be round (for icon-only buttons)
          * @default false
         */
        "circle": boolean;
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Download attribute for link buttons
         */
        "download": string;
        /**
          * Form ID to associate with
         */
        "form": string;
        /**
          * Form action override
         */
        "formAction": string;
        /**
          * Form encoding type override
         */
        "formEnctype": | 'application/x-www-form-urlencoded'
    | 'multipart/form-data'
    | 'text/plain';
        /**
          * Form method override
         */
        "formMethod": 'post' | 'get';
        /**
          * Form no validate override
          * @default false
         */
        "formNoValidate": boolean;
        /**
          * Form target override
         */
        "formTarget": '_self' | '_blank' | '_parent' | '_top' | string;
        /**
          * Whether the button should be full width
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Link URL (renders as anchor when provided)
         */
        "href": string;
        /**
          * Minimum width for the button
         */
        "minWidth": string;
        /**
          * Button name for form submission
         */
        "name": string;
        /**
          * Whether the button is outlined
          * @default false
         */
        "outline": boolean;
        /**
          * Whether the button should be pill-shaped
          * @default false
         */
        "pill": boolean;
        /**
          * Rel attribute for link buttons
         */
        "rel": string;
        /**
          * The size of the button (small, medium, large)
          * @default 'medium'
         */
        "size": SlButton['size'];
        /**
          * Target for link buttons
         */
        "target": '_blank' | '_parent' | '_self' | '_top';
        /**
          * The text content of the button
          * @default 'Button'
         */
        "text": string;
        /**
          * The type of button (primary, secondary, destructive)
          * @default 'button'
         */
        "type": SlButton['type'];
        /**
          * Button value for form submission
         */
        "value": string;
        /**
          * The variant of the button (filled, outlined, ghost)
          * @default 'default'
         */
        "variant": SlButton['variant'];
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSharedSidebarElement extends Components.SharedSidebar, HTMLStencilElement {
    }
    var HTMLSharedSidebarElement: {
        prototype: HTMLSharedSidebarElement;
        new (): HTMLSharedSidebarElement;
    };
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "shared-sidebar": HTMLSharedSidebarElement;
        "ui-button": HTMLUiButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SharedSidebar {
        /**
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * @default []
         */
        "sections"?: SidebarSection[];
    }
    interface UiButton {
        /**
          * Whether the button should have a caret
          * @default false
         */
        "caret"?: boolean;
        /**
          * Whether the button should be round (for icon-only buttons)
          * @default false
         */
        "circle"?: boolean;
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Download attribute for link buttons
         */
        "download"?: string;
        /**
          * Form ID to associate with
         */
        "form"?: string;
        /**
          * Form action override
         */
        "formAction"?: string;
        /**
          * Form encoding type override
         */
        "formEnctype"?: | 'application/x-www-form-urlencoded'
    | 'multipart/form-data'
    | 'text/plain';
        /**
          * Form method override
         */
        "formMethod"?: 'post' | 'get';
        /**
          * Form no validate override
          * @default false
         */
        "formNoValidate"?: boolean;
        /**
          * Form target override
         */
        "formTarget"?: '_self' | '_blank' | '_parent' | '_top' | string;
        /**
          * Whether the button should be full width
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Link URL (renders as anchor when provided)
         */
        "href"?: string;
        /**
          * Minimum width for the button
         */
        "minWidth"?: string;
        /**
          * Button name for form submission
         */
        "name"?: string;
        /**
          * Whether the button is outlined
          * @default false
         */
        "outline"?: boolean;
        /**
          * Whether the button should be pill-shaped
          * @default false
         */
        "pill"?: boolean;
        /**
          * Rel attribute for link buttons
         */
        "rel"?: string;
        /**
          * The size of the button (small, medium, large)
          * @default 'medium'
         */
        "size"?: SlButton['size'];
        /**
          * Target for link buttons
         */
        "target"?: '_blank' | '_parent' | '_self' | '_top';
        /**
          * The text content of the button
          * @default 'Button'
         */
        "text"?: string;
        /**
          * The type of button (primary, secondary, destructive)
          * @default 'button'
         */
        "type"?: SlButton['type'];
        /**
          * Button value for form submission
         */
        "value"?: string;
        /**
          * The variant of the button (filled, outlined, ghost)
          * @default 'default'
         */
        "variant"?: SlButton['variant'];
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "shared-sidebar": SharedSidebar;
        "ui-button": UiButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "shared-sidebar": LocalJSX.SharedSidebar & JSXBase.HTMLAttributes<HTMLSharedSidebarElement>;
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
        }
    }
}
